### ISSUE TITLE
Doesn't work in case of type reference instead of inner struct

### ISSUE THREAD

**Issue by sadensmol** [Esequiel378/mapper#1]
At the moment when you use some custom type you have to enclose it within the struct e.g.
type BirthDay  struct {
   time.Time
}

but it's better in this case to use just type reference:
type BirthDay  time.Time

Same for string based types like
ABCFlag string

I would like to have custom unmarshallers for such type references.
Any plans to add it?? Thanks.

**Comment by Esequiel378** [comment]
Hello there! The library already supports custom unmarshalling on type aliases!

[Unit test](https://github.com/Esequiel378/fixedlength/blob/74b6ee98a04b8ebf7c42a3b6fd17d7d3ce3e6d5f/decode_test.go#L178)

```go
// ABCCustom accepts ABC strings, any other value will be ignored
// and the value will be set to an empty string.
type ABCCustom string

var _ Unmarshaler = (*ABCCustom)(nil)

func (ac *ABCCustom) Unmarshal(data []byte) error {
	if string(data) == "ABC" {
		*ac = ABCCustom(data)
	}

	return nil
}
```
